### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by Izuyazep** [Smug246/Luna-Token-Grabber#59]
Nothing is sent to the webhook

**Comment by Smug246** [comment]
can you give me a bit more info than that. Any error?

**Comment by Izuyazep** [comment]
Yes here look 

![image](https://user-images.githubusercontent.com/96847178/201526322-cf9513bc-d100-49e7-be34-d985511ec67d.png)

**Comment by Smug246** [comment]
lmao read the template before you make an issue but thanks ill look into it

**Comment by Smug246** [comment]
make sure you have latest version of pyinstaller and try latest update

**Comment by Izuyazep** [comment]
I already have the latest version of everything and when I compile to exe it takes like 2 minutes which mean there is a problem and wheel doesn't want to be downloaded look

**Comment by Izuyazep** [comment]
![image](https://user-images.githubusercontent.com/96847178/201775268-d269a23e-6eb8-4a20-b65b-2c6f9e637586.png)

**Comment by Izuyazep** [comment]
When it converts to exe it stays stuck for 1 minute in here 
![image](https://user-images.githubusercontent.com/96847178/201775661-0022fa46-a8fb-4a9b-b60f-b1c691d91d39.png)

**Comment by Smug246** [comment]
use your eyes 
![image](https://user-images.githubusercontent.com/99215486/202247077-728e904a-999a-4e6a-9946-8b2a44929ba7.png)

**Comment by KingKrex69** [comment]
> ![image](https://user-images.githubusercontent.com/96847178/201775268-d269a23e-6eb8-4a20-b65b-2c6f9e637586.png)

Download the latest version of windows 10 SDK from Visual Studio and it should be fixed

**Comment by Izuyazep** [comment]
> > ![image](https://user-images.githubusercontent.com/96847178/201775268-d269a23e-6eb8-4a20-b65b-2c6f9e637586.png)
> 
> Download the latest version of windows 10 SDK from Visual Studio and it should be fixed

it's still not fixed I download the professional sutdio code with windows 10 sdk_

**Comment by KingKrex69** [comment]
> > > ![image](https://user-images.githubusercontent.com/96847178/201775268-d269a23e-6eb8-4a20-b65b-2c6f9e637586.png)
> > 
> > 
> > Download the latest version of windows 10 SDK from Visual Studio and it should be fixed
> 
> it's still not fixed I download the professional sutdio code with windows 10 sdk_

try `pip install pyproject.toml` or `pip install --upgrade pyproject.toml`

**Comment by Izuyazep** [comment]
> 

already satisfied with that I tried to downgrade to python 3.10 and it worked but nothing got sent to the webhook so I went back to python 3.11
